name: mini_campus_core
description: MiniCampus core shared components
version: 0.0.1
homepage: https://github.com/DonnC-Lab
publish_to: none

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # firebase | google
  cloud_firestore: ^3.1.10
  firebase_auth: ^3.3.9
  firebase_core: ^1.13.1
  firebase_storage: ^10.2.9
  firebase_messaging: ^11.2.8
  firebase_database: ^9.0.8
  flutterfire_ui: ^0.3.6

  # icons
  cupertino_icons: ^1.0.2
  flutter_vector_icons: ^1.0.0
  flutter_svg: ^1.0.3

  # file IO
  image_picker: ^0.8.4+11
  file_picker: ^4.5.1

  # state management
  flutter_riverpod: ^2.0.0-dev.4

  # notification
  fluttertoast: ^8.0.9
  flash: ^2.0.3+2
  awesome_notifications: ^0.6.21

  # utilities
  dio: ^4.0.4
  freezed_annotation: ^1.1.0
  timeago: ^3.2.2
  url_launcher: ^6.0.20
  shared_preferences: ^2.0.13
  linkable: ^3.0.1
  google_fonts: ^2.3.1
  relative_scale: ^2.0.0
  localregex: ^3.0.3
  timer_button:
  intl:
  flutter_advanced_avatar: ^1.0.0+1
  numeral: ^2.0.1

  # misc
  intro_slider: ^3.0.4
  json_annotation: ^4.4.0
  fancy_shimmer_image: ^2.0.2
  flutter_cache_manager: ^3.3.0

  # browser
  flutter_web_browser: ^0.17.1

  # components
  flutter_form_builder: ^7.1.1
  form_builder_validators: ^7.7.0
  keyboard_actions: ^3.4.7
  animate_do: ^2.1.0
  circular_clip_route: ^0.2.0+2
  modal_bottom_sheet: ^2.0.1
  page_transition: ^2.0.5
  phone_number: ^0.12.0+1
  photo_view: ^0.13.0

  # custom libs
  mini_campus_core_libs:
    git: git//github.com/DonnC-Lab/mini_campus_core_libs.git

  mc_core_constants:
    git: git//github.com/DonnC-Lab/mc_core_constants.git

  mini_campus_core_components:
    git: git//github.com/DonnC-Lab/mini_campus_core_components.git

dev_dependencies:
  build_runner: null
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed:
  json_serializable: ^6.1.4


# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/onboarding/


